# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - 5433:5432
  
volumes:
    db_data:

